services:
  database:
    image : postgres
    restart: always
    environment:
      POSTGRES_USER : user
      POSTGRES_PASSWORD : pasword
      POSTGRES_DB : myapp
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  app : 
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  db_data: